dist: bionic
language: ruby
jobs:
  include:
    - rvm: 2.7
      gemfile: Gemfile
    - rvm: 2.6
      gemfile: test/gemfiles/rails52.gemfile
    - rvm: 2.5
      gemfile: test/gemfiles/rails51.gemfile
    - rvm: 2.4
      gemfile: test/gemfiles/rails50.gemfile
    - name: MariaDB
      rvm: 2.7
      gemfile: Gemfile
      addons:
        mariadb: 10.3
        postgresql: 10
      before_script:
        - mysqladmin create ahoy_test
        - mysql -e 'create user travis@localhost;'
        - mysql -e 'grant all on *.* to travis@localhost;'
        - createdb ahoy_test
      services:
        - postgresql
        - mariadb
        - mongodb
addons:
  postgresql: 10
services:
  - postgresql
  - mysql
  - mongodb
script: bundle exec rake test test:query_methods
before_install:
  - mysqladmin create ahoy_test
  - createdb ahoy_test
notifications:
  email:
    on_success: never
    on_failure: change
