dist: xenial
language: ruby
rvm: 2.6.3
gemfile: Gemfile
services:
  - postgresql
  - mysql
  - mongodb
script: bundle exec rake test
before_install:
  - mysql -e 'CREATE DATABASE ahoy_test;'
  - psql -c 'CREATE DATABASE ahoy_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
