dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
  - test/gemfiles/rails52.gemfile
services:
  - postgresql
  - mysql
  - mongodb
script: bundle exec rake test
before_install:
  - mysqladmin create ahoy_test
  - createdb ahoy_test
notifications:
  email:
    on_success: never
    on_failure: change
